#### spring config
server:
  port: 8081

#### spring & mysql cred
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yt_clone?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: springRestAPI
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show:
      sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB





